In [12]:
import pandas as pd
df = pd.read_csv('iphone.csv')
df

,Product Name,Product URL,Brand,Sale Price,Mrp,Number Of Ratings,Number Of Reviews,Upc,Star Rating,Ram
0,"APPLE iPhone 8 Plus (Gold, 64 GB)",https://www.flipkart.com/apple-iphone-8-plus-g...,Apple,49900,49900,3431,356,MOBEXRGV7EHHTGUH,4.6,2 GB
1,"APPLE iPhone 8 Plus (Space Grey, 256 GB)",https://www.flipkart.com/apple-iphone-8-plus-s...,Apple,84900,84900,3431,356,MOBEXRGVAC6TJT4F,4.6,2 GB
2,"APPLE iPhone 8 Plus (Silver, 256 GB)",https://www.flipkart.com/apple-iphone-8-plus-s...,Apple,84900,84900,3431,356,MOBEXRGVGETABXWZ,4.6,2 GB
3,"APPLE iPhone 8 (Silver, 256 GB)",https://www.flipkart.com/apple-iphone-8-silver...,Apple,77000,77000,11202,794,MOBEXRGVMZWUHCBA,NaN,2 GB
4,"APPLE iPhone 8 (Gold, 256 GB)",https://www.flipkart.com/apple-iphone-8-gold-2...,Apple,77000,77000,11202,794,MOBEXRGVPK7PFEJZ,4.5,2 GB
...,...,...,...,...,...,...,...,...,...,...
57,"APPLE iPhone SE (Black, 64 GB)",https://www.flipkart.com/apple-iphone-se-black...,Apple,29999,39900,95909,8161,MOBFWQ6BR3MK7AUG,4.5,4 GB
58,"APPLE iPhone 11 (Purple, 64 GB)",https://www.flipkart.com/apple-iphone-11-purpl...,Apple,46999,54900,43470,3331,MOBFWQ6BTFFJKGKE,4.6,4 GB
59,"APPLE iPhone 11 (White, 64 GB)",https://www.flipkart.com/apple-iphone-11-white...,Apple,46999,54900,43470,3331,MOBFWQ6BVWVEH3XE,4.6,4 GB
60,"APPLE iPhone 11 (Black, 64 GB)",https://www.flipkart.com/apple-iphone-11-black...,Apple,46999,54900,43470,3331,MOBFWQ6BXGJCEYNY,4.6,4 GB
61,"APPLE iPhone 11 (Red, 64 GB)",https://www.flipkart.com/apple-iphone-11-red-6...,Apple,46999,54900,43470,3331,MOBFWQ6BYYV3FCU7,4.6,4 GB

In [7]:
# 1 - The column names have spaces . rename the column names to have underscore 
# '_' instead of space (try to do in one go instead of specifying each column nam in rename method)

df.columns = df.columns.str.replace(' ','_')
df

,Product_Name,Product_URL,Brand,Sale_Price,Mrp,Number_Of_Ratings,Number_Of_Reviews,Upc,Star_Rating,Ram
0,"APPLE iPhone 8 Plus (Gold, 64 GB)",https://www.flipkart.com/apple-iphone-8-plus-g...,Apple,49900,49900,3431,356,MOBEXRGV7EHHTGUH,4.6,2 GB
1,"APPLE iPhone 8 Plus (Space Grey, 256 GB)",https://www.flipkart.com/apple-iphone-8-plus-s...,Apple,84900,84900,3431,356,MOBEXRGVAC6TJT4F,4.6,2 GB
2,"APPLE iPhone 8 Plus (Silver, 256 GB)",https://www.flipkart.com/apple-iphone-8-plus-s...,Apple,84900,84900,3431,356,MOBEXRGVGETABXWZ,4.6,2 GB
3,"APPLE iPhone 8 (Silver, 256 GB)",https://www.flipkart.com/apple-iphone-8-silver...,Apple,77000,77000,11202,794,MOBEXRGVMZWUHCBA,NaN,2 GB
4,"APPLE iPhone 8 (Gold, 256 GB)",https://www.flipkart.com/apple-iphone-8-gold-2...,Apple,77000,77000,11202,794,MOBEXRGVPK7PFEJZ,4.5,2 GB
...,...,...,...,...,...,...,...,...,...,...
57,"APPLE iPhone SE (Black, 64 GB)",https://www.flipkart.com/apple-iphone-se-black...,Apple,29999,39900,95909,8161,MOBFWQ6BR3MK7AUG,4.5,4 GB
58,"APPLE iPhone 11 (Purple, 64 GB)",https://www.flipkart.com/apple-iphone-11-purpl...,Apple,46999,54900,43470,3331,MOBFWQ6BTFFJKGKE,4.6,4 GB
59,"APPLE iPhone 11 (White, 64 GB)",https://www.flipkart.com/apple-iphone-11-white...,Apple,46999,54900,43470,3331,MOBFWQ6BVWVEH3XE,4.6,4 GB
60,"APPLE iPhone 11 (Black, 64 GB)",https://www.flipkart.com/apple-iphone-11-black...,Apple,46999,54900,43470,3331,MOBFWQ6BXGJCEYNY,4.6,4 GB
61,"APPLE iPhone 11 (Red, 64 GB)",https://www.flipkart.com/apple-iphone-11-red-6...,Apple,46999,54900,43470,3331,MOBFWQ6BYYV3FCU7,4.6,4 GB

In [11]:
# 2- start rating for some of the models is missing in the dataset. 
# fill those missing values with the average rating all the models.

average_rating = df['Star_Rating'].mean(skipna=True)

df['Star_Rating'].fillna(average_rating, inplace=True)

df

C:\Users\91828\AppData\Local\Temp\ipykernel_94380\2397110781.py:6: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Star_Rating'].fillna(average_rating, inplace=True)

,Product_Name,Product_URL,Brand,Sale_Price,Mrp,Number_Of_Ratings,Number_Of_Reviews,Upc,Star_Rating,Ram
0,"APPLE iPhone 8 Plus (Gold, 64 GB)",https://www.flipkart.com/apple-iphone-8-plus-g...,Apple,49900,49900,3431,356,MOBEXRGV7EHHTGUH,4.600000,2 GB
1,"APPLE iPhone 8 Plus (Space Grey, 256 GB)",https://www.flipkart.com/apple-iphone-8-plus-s...,Apple,84900,84900,3431,356,MOBEXRGVAC6TJT4F,4.600000,2 GB
2,"APPLE iPhone 8 Plus (Silver, 256 GB)",https://www.flipkart.com/apple-iphone-8-plus-s...,Apple,84900,84900,3431,356,MOBEXRGVGETABXWZ,4.600000,2 GB
3,"APPLE iPhone 8 (Silver, 256 GB)",https://www.flipkart.com/apple-iphone-8-silver...,Apple,77000,77000,11202,794,MOBEXRGVMZWUHCBA,4.576271,2 GB
4,"APPLE iPhone 8 (Gold, 256 GB)",https://www.flipkart.com/apple-iphone-8-gold-2...,Apple,77000,77000,11202,794,MOBEXRGVPK7PFEJZ,4.500000,2 GB
...,...,...,...,...,...,...,...,...,...,...
57,"APPLE iPhone SE (Black, 64 GB)",https://www.flipkart.com/apple-iphone-se-black...,Apple,29999,39900,95909,8161,MOBFWQ6BR3MK7AUG,4.500000,4 GB
58,"APPLE iPhone 11 (Purple, 64 GB)",https://www.flipkart.com/apple-iphone-11-purpl...,Apple,46999,54900,43470,3331,MOBFWQ6BTFFJKGKE,4.600000,4 GB
59,"APPLE iPhone 11 (White, 64 GB)",https://www.flipkart.com/apple-iphone-11-white...,Apple,46999,54900,43470,3331,MOBFWQ6BVWVEH3XE,4.600000,4 GB
60,"APPLE iPhone 11 (Black, 64 GB)",https://www.flipkart.com/apple-iphone-11-black...,Apple,46999,54900,43470,3331,MOBFWQ6BXGJCEYNY,4.600000,4 GB
61,"APPLE iPhone 11 (Red, 64 GB)",https://www.flipkart.com/apple-iphone-11-red-6...,Apple,46999,54900,43470,3331,MOBFWQ6BYYV3FCU7,4.600000,4 GB

In [42]:
# 3- Now instead of filling missing values with avg rating of full dataset , 
# fill with avg rating based on RAM. example :  if rating for a 2 gb phone is missing then take 
# average of all other 2 gb phones rating and fill that value. 

# Function to fill missing ratings based on RAM
def fill_missing_rating(row):
    if pd.isna(row['Star Rating']):
        return average_ratings_by_ram.get(row['RAM'], None)
    return row['Star Rating']

# Apply the function to fill missing ratings
df['Star Rating'] = df.apply(fill_missing_rating, axis=1)

# Display the modified DataFrame
print(df)

                                Product Name  \
0          APPLE iPhone 8 Plus (Gold, 64 GB)
1   APPLE iPhone 8 Plus (Space Grey, 256 GB)
2       APPLE iPhone 8 Plus (Silver, 256 GB)
3            APPLE iPhone 8 (Silver, 256 GB)
4              APPLE iPhone 8 (Gold, 256 GB)
..                                       ...
57            APPLE iPhone SE (Black, 64 GB)
58           APPLE iPhone 11 (Purple, 64 GB)
59            APPLE iPhone 11 (White, 64 GB)
60            APPLE iPhone 11 (Black, 64 GB)
61              APPLE iPhone 11 (Red, 64 GB)

                                          Product URL  Brand  Sale Price  \
0   https://www.flipkart.com/apple-iphone-8-plus-g...  Apple       49900
1   https://www.flipkart.com/apple-iphone-8-plus-s...  Apple       84900
2   https://www.flipkart.com/apple-iphone-8-plus-s...  Apple       84900
3   https://www.flipkart.com/apple-iphone-8-silver...  Apple       77000
4   https://www.flipkart.com/apple-iphone-8-gold-2...  Apple       77000
..                                                ...    ...         ...
57  https://www.flipkart.com/apple-iphone-se-black...  Apple       29999
58  https://www.flipkart.com/apple-iphone-11-purpl...  Apple       46999
59  https://www.flipkart.com/apple-iphone-11-white...  Apple       46999
60  https://www.flipkart.com/apple-iphone-11-black...  Apple       46999
61  https://www.flipkart.com/apple-iphone-11-red-6...  Apple       46999

      Mrp  Number Of Ratings  Number Of Reviews               Upc  \
0   49900               3431                356  MOBEXRGV7EHHTGUH
1   84900               3431                356  MOBEXRGVAC6TJT4F
2   84900               3431                356  MOBEXRGVGETABXWZ
3   77000              11202                794  MOBEXRGVMZWUHCBA
4   77000              11202                794  MOBEXRGVPK7PFEJZ
..    ...                ...                ...               ...
57  39900              95909               8161  MOBFWQ6BR3MK7AUG
58  54900              43470               3331  MOBFWQ6BTFFJKGKE
59  54900              43470               3331  MOBFWQ6BVWVEH3XE
60  54900              43470               3331  MOBFWQ6BXGJCEYNY
61  54900              43470               3331  MOBFWQ6BYYV3FCU7

    Star Rating   Ram  Average Rating_x  Average Rating_y  Average Rating
0      4.600000  2 GB          4.541667          4.541667        4.541667
1      4.600000  2 GB          4.541667          4.541667        4.541667
2      4.600000  2 GB          4.541667          4.541667        4.541667
3      4.541667  2 GB          4.541667          4.541667        4.541667
4      4.500000  2 GB          4.541667          4.541667        4.541667
..          ...   ...               ...               ...             ...
57     4.500000  4 GB          4.589286          4.589286        4.589286
58     4.600000  4 GB          4.589286          4.589286        4.589286
59     4.600000  4 GB          4.589286          4.589286        4.589286
60     4.600000  4 GB          4.589286          4.589286        4.589286
61     4.600000  4 GB          4.589286          4.589286        4.589286

[62 rows x 13 columns]

In [45]:
# 4- create a new column in the dataframe "Discount_Percentage" based on MRP and sale value.

df['Discount_Percentage'] = ((df['Mrp']-df['Sale Price']) / df['Mrp']) * 100
df

,Product Name,Product URL,Brand,Sale Price,Mrp,Number Of Ratings,Number Of Reviews,Upc,Star Rating,Ram,Average Rating_x,Average Rating_y,Average Rating,Discount_Percentage
0,"APPLE iPhone 8 Plus (Gold, 64 GB)",https://www.flipkart.com/apple-iphone-8-plus-g...,Apple,49900,49900,3431,356,MOBEXRGV7EHHTGUH,4.600000,2 GB,4.541667,4.541667,4.541667,0.000000
1,"APPLE iPhone 8 Plus (Space Grey, 256 GB)",https://www.flipkart.com/apple-iphone-8-plus-s...,Apple,84900,84900,3431,356,MOBEXRGVAC6TJT4F,4.600000,2 GB,4.541667,4.541667,4.541667,0.000000
2,"APPLE iPhone 8 Plus (Silver, 256 GB)",https://www.flipkart.com/apple-iphone-8-plus-s...,Apple,84900,84900,3431,356,MOBEXRGVGETABXWZ,4.600000,2 GB,4.541667,4.541667,4.541667,0.000000
3,"APPLE iPhone 8 (Silver, 256 GB)",https://www.flipkart.com/apple-iphone-8-silver...,Apple,77000,77000,11202,794,MOBEXRGVMZWUHCBA,4.541667,2 GB,4.541667,4.541667,4.541667,0.000000
4,"APPLE iPhone 8 (Gold, 256 GB)",https://www.flipkart.com/apple-iphone-8-gold-2...,Apple,77000,77000,11202,794,MOBEXRGVPK7PFEJZ,4.500000,2 GB,4.541667,4.541667,4.541667,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
57,"APPLE iPhone SE (Black, 64 GB)",https://www.flipkart.com/apple-iphone-se-black...,Apple,29999,39900,95909,8161,MOBFWQ6BR3MK7AUG,4.500000,4 GB,4.589286,4.589286,4.589286,24.814536
58,"APPLE iPhone 11 (Purple, 64 GB)",https://www.flipkart.com/apple-iphone-11-purpl...,Apple,46999,54900,43470,3331,MOBFWQ6BTFFJKGKE,4.600000,4 GB,4.589286,4.589286,4.589286,14.391621
59,"APPLE iPhone 11 (White, 64 GB)",https://www.flipkart.com/apple-iphone-11-white...,Apple,46999,54900,43470,3331,MOBFWQ6BVWVEH3XE,4.600000,4 GB,4.589286,4.589286,4.589286,14.391621
60,"APPLE iPhone 11 (Black, 64 GB)",https://www.flipkart.com/apple-iphone-11-black...,Apple,46999,54900,43470,3331,MOBFWQ6BXGJCEYNY,4.600000,4 GB,4.589286,4.589286,4.589286,14.391621
61,"APPLE iPhone 11 (Red, 64 GB)",https://www.flipkart.com/apple-iphone-11-red-6...,Apple,46999,54900,43470,3331,MOBFWQ6BYYV3FCU7,4.600000,4 GB,4.589286,4.589286,4.589286,14.391621

In [52]:
# 5- which model has highest percent discount ?

sorted_df = df.sort_values(by='Discount_Percentage',ascending=False)

# Get the model with the highest discount and its corresponding percentage

model_with_hieght_discount = sorted_df.iloc[0]['Product Name']
hieghtest_discount = sorted_df.iloc[0]['Discount_Percentage']

'APPLE iPhone 11 Pro (Midnight Green, 64 GB)'

In [59]:
# 6- find total no of models  each space configuration (128 GB , 64 GB etc)

space_configuration_counts = df['Ram'].value_counts()

# Rename the columns for clarity

space_configuration_counts.columns = ['space Configuration', 'Total Models']

In [61]:
# 9- list top 5 models having highest no of reviews

# Sort the DataFrame by 'Number Of Reviews' in descending order

df_sorted = df.sort_values(by='Number Of Reviews', ascending=False)

# Select the top 5 models with the highest number of reviews

top_5_models = df_sorted.head(5)

top_5_models

,Product Name,Product URL,Brand,Sale Price,Mrp,Number Of Ratings,Number Of Reviews,Upc,Star Rating,Ram,Average Rating_x,Average Rating_y,Average Rating,Discount_Percentage
23,"Apple iPhone SE (White, 256 GB)",https://www.flipkart.com/apple-iphone-se-white...,Apple,44999,54900,95909,8161,MOBFRFXHPZCHAPEH,4.5,2 GB,4.541667,4.541667,4.541667,18.034608
53,"APPLE iPhone SE (Black, 128 GB)",https://www.flipkart.com/apple-iphone-se-black...,Apple,34999,44900,95909,8161,MOBFWQ6BHUEVZPXD,4.5,2 GB,4.541667,4.541667,4.541667,22.051225
55,"APPLE iPhone SE (Red, 128 GB)",https://www.flipkart.com/apple-iphone-se-red-1...,Apple,34999,44900,95909,8161,MOBFWQ6BJTVFKPEJ,4.5,2 GB,4.541667,4.541667,4.541667,22.051225
57,"APPLE iPhone SE (Black, 64 GB)",https://www.flipkart.com/apple-iphone-se-black...,Apple,29999,39900,95909,8161,MOBFWQ6BR3MK7AUG,4.5,4 GB,4.589286,4.589286,4.589286,24.814536
52,"APPLE iPhone SE (White, 64 GB)",https://www.flipkart.com/apple-iphone-se-white...,Apple,29999,39900,95807,8154,MOBFWQ6BGWDVGF3E,4.5,2 GB,4.541667,4.541667,4.541667,24.814536

In [65]:
# 10 - what is the price diffrence between highest price and lowest price iphone (based on mrp)

highest_mrp = df['Mrp'].max()
lowest_mrp = df['Mrp'].min()

# Calculate the price difference

price_difference = highest_mrp - lowest_mrp
price_difference

110000

In [67]:
# 12- which iphone has 3rd highest MRP

# Sort the DataFrame by 'Mrp' column in descending order and reset the index
sorted_df = df.sort_values(by='Mrp',ascending=False).reset_index(drop=True)

# Get the iPhone with the 3rd highest MRP
third_highest_mrp_iphone = sorted_df.loc[2]

# Print the details of the iPhone with the 3rd highest MRP
print(third_highest_mrp_iphone)

Product Name                APPLE iPhone 11 Pro (Midnight Green, 512 GB)
Product URL            https://www.flipkart.com/apple-iphone-11-pro-m...
Brand                                                              Apple
Sale Price                                                        117900
Mrp                                                               140300
Number Of Ratings                                                   7088
Number Of Reviews                                                    523
Upc                                                     MOBFKCTSSJCWYGCC
Star Rating                                                          4.6
Ram                                                                 4 GB
Average Rating_x                                                4.589286
Average Rating_y                                                4.589286
Average Rating                                                  4.589286
Discount_Percentage                                            15.965788
Name: 2, dtype: object

In [70]:
# 13- what is the average mrp of iphones which costs above 100,000

# Filter the DataFrame to include only iPhones with MRP above 100,000

high_mrp_iphone = df[df['Mrp']>100000]

# Calculate the average MRP for the filtered iPhones

average_mrp = high_mrp_iphone['Mrp'].mean()

print(average_mrp)

130559.09090909091

In [74]:
# 14- which iphone with 128 GB space has highest ratings to review ratio

# Filter the DataFrame to include only iPhones with 128 GB of space

iphone_128gb = df[df['Ram'] == '128 GB']

# Calculate the ratings-to-reviews ratio for each iPhone

iphone_128gb['Rating to review Ratio'] = iphone_128gb['Number Of Ratings'] / iphone_128gb['Number Of Reviews']

# Find the iPhone with the highest ratings-to-reviews ratio

highest_ratio_iphone = iphone_128gb.loc[iphone_128gb['Rating to review Ratio'].idmax()]

AttributeError: 'Series' object has no attribute 'idmax'